name: genieacs
services:
  genieacs:
    cpu_shares: 90
    command: []
    container_name: genieacs
    depends_on:
      mongo:
        condition: service_started
        required: true
    deploy:
      resources:
        limits:
          memory: 1024M
    environment:
      - GENIEACS_CWMP_ACCESS_LOG_FILE=/var/log/genieacs/genieacs-cwmp-access.log
      - GENIEACS_DEBUG_FILE=/var/log/genieacs/genieacs-debug.yaml
      - GENIEACS_EXT_DIR=/opt/genieacs/ext
      - GENIEACS_FS_ACCESS_LOG_FILE=/var/log/genieacs/genieacs-fs-access.log
      - GENIEACS_MONGODB_CONNECTION_URL=mongodb://mongo/genieacs
      - GENIEACS_NBI_ACCESS_LOG_FILE=/var/log/genieacs/genieacs-nbi-access.log
      - GENIEACS_UI_ACCESS_LOG_FILE=/var/log/genieacs/genieacs-ui-access.log
      - GENIEACS_UI_JWT_SECRET=<MASUKKAN JWT SECRET KEY>
    image: drumsergio/genieacs:latest
    labels:
      icon: https://genieacs.com/images/favicon.png
    ports:
      - target: 7547
        published: "7547"
        protocol: tcp
      - target: 7557
        published: "7557"
        protocol: tcp
      - target: 7567
        published: "7567"
        protocol: tcp
      - target: 3000
        published: "3000"
        protocol: tcp
    restart: always
    volumes: []
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    networks:
      - genieacs_network
    privileged: false
  mongo:
    cpu_shares: 90
    command: []
    container_name: mongo-genieacs
    deploy:
      resources:
        limits:
          memory: 1024M
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/var/log/mongodb
    expose:
      - "27017"
    image: mongo:4.4.6
    labels:
      icon: https://genieacs.com/images/favicon.png
    restart: always
    ports: []
    volumes: []
    devices: []
    cap_add: []
    networks:
      - genieacs_network
    privileged: false
networks:
  genieacs_network:
    name: genieacs_network
x-casaos:
  author: self
  category: self
  hostname: ""
  icon: https://genieacs.com/images/favicon.png
  index: /
  port_map: "3000"
  scheme: http
  store_app_id: genieacs
  title:
    custom: Genieacs
